#!/usr/bin/python3
# encoding=UTF-8

# Copyright © 2014-2023 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import argparse
import errno
import functools
import os
import pathlib
import shutil
import subprocess as ipc
import tempfile

import debian.deb822 as deb

int(0_0)  # Python >= 3.6 is required

def get_dpkg_architecture():
    cmdline = ['dpkg', '--print-architecture']
    output = ipc.check_output(cmdline)
    return output.strip().decode('ASCII')

class Package():

    def __init__(self, name, architecture, *, essential=False, depends='', pre_depends=''):
        self.name = name
        self.architecture = architecture
        self.essential = essential
        depends = str.join(', ', (
            d for d in [depends, pre_depends] if d
        ))
        depends = depends.replace(':any', '')  # FIXME
        if depends:
            self.depends = deb.PkgRelation.parse_relations(depends)
        else:
            self.depends = []

    def __str__(self):
        if self.architecture == 'all':
            return self.name
        return f'{self.name}:{self.architecture}'

def get_packages():
    dpkg_architecture = get_dpkg_architecture()
    cmdline = [
        'dpkg-query',
        '-Wf', '${Package}\t${Architecture}\t${Essential}\t${Provides}\t${Depends}\t${Pre-Depends}\n',
        '*:all',
        f'*:{dpkg_architecture}',  # multiarch is hard, let's go shopping
    ]
    output = ipc.check_output(cmdline)
    pkginfo = output.decode('ASCII').splitlines()
    packages = {}
    for line in pkginfo:
        name, architecture, essential, provides, depends, pre_depends = line.split('\t')
        essential = essential == 'yes'
        pkg = Package(name, architecture,
            essential=essential,
            depends=depends,
            pre_depends=pre_depends
        )
        packages[name] = pkg
        provides = [
            p.strip().split(' ', 1)[0]
            for p in provides.split(',')
        ]
        for name in provides:
            packages[name] = pkg
    return packages

def create_apt_pool(packages, path):
    cmdline = ['dpkg-repack', '-d', '-Znone'] + [str(p) for p in packages]
    if os.getuid() != 0:
        cmdline[:0] = ['fakeroot', '-u']
    ipc.check_call(
        cmdline,
        preexec_fn=functools.partial(os.chdir, path)
    )

apt_ftparchive_config_template = r'''
Dir {{
    ArchiveDir "{root}";
    CacheDir "{root}/cache/";
}};

TreeDefault {{
    Directory "pool/";
    Packages "$(DIST)/$(SECTION)/binary-$(ARCH)/Packages";
}};

Tree "dists/unstable" {{
    Sections "main";
    Architectures "{arch}";
}}

APT::FTPArchive::Release {{
    Suite "unstable";
    Codename "sid";
    Origin "demoostrap";
    Components "main";
    Architectures "{arch} all";
}}
'''

mkdir_p = functools.partial(os.makedirs, exist_ok=True)

def rm_f(path):
    try:
        os.unlink(path)
    except OSError as exc:
        if exc.errno == errno.ENOENT:
            return
        raise

def create_apt_archive(packages, path):
    root = path
    mkdir_p(root)
    pool_path = f'{root}/pool'
    mkdir_p(pool_path)
    create_apt_pool(packages, pool_path)
    [architecture] = {
        pkg.architecture
        for pkg in packages
        if pkg.architecture != 'all'
    }
    config = apt_ftparchive_config_template.format(
        root=root,
        arch=architecture,
    )
    config_path = f'{root}/config'
    with open(config_path, 'wt', encoding='ASCII') as config_file:
        config_file.write(config)
    cache_path = f'{root}/cache'
    mkdir_p(cache_path)
    dist_path = f'{root}/dists/unstable'
    bin_dist_path = f'{dist_path}/main/binary-{architecture}'
    mkdir_p(bin_dist_path)
    cmdline = ['apt-ftparchive', 'generate', '--no-contents', config_path]
    ipc.check_call(cmdline)
    release_path = f'{dist_path}/Release'
    rm_f(release_path)  # bug #317661
    cmdline = ['apt-ftparchive', 'release', '--config-file', config_path, dist_path]
    output = ipc.check_output(cmdline)
    with open(release_path, 'wb') as release:
        release.write(output)

def debootstrap(repository, target, *, include=None, no_root=False):
    cmdline = [
        '/usr/sbin/debootstrap',
        '--no-check-gpg',
        'unstable',
        target,
        'file:' + repository,
    ]
    if include:
        cmdline[1:1] = ['--include', include]
    if no_root:
        cmdline[:0] = ['fakeroot', 'fakechroot']
    ipc.check_call(cmdline)

def error(message):
    ap = argparse.ArgumentParser()
    prog = ap.prog
    message = str.join('', (prog, ': error: ', message, '\n'))
    ap.exit(1, message)

def ensure_cmds_exist(*cmds):
    for cmd in cmds:
        if shutil.which(cmd) is None:
            error('command not found: ' + cmd)

def mkemptydir(path):
    path = pathlib.Path(path)
    try:
        path.mkdir(exist_ok=True)
    except OSError as exc:
        error(f'{path}: {exc.strerror}')
    with os.scandir(path) as scan_path:
        for _item in scan_path:
            error(f'{path}: directory not empty')

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('target', metavar='TARGET', help='bootstrap into this directory')
    ap.add_argument('--include', metavar='PKG[,PKG...]', default='', help='install these packages too')
    ap.add_argument('-u', action='store_true', help='bootstrap as normal user')
    options = ap.parse_args()
    ensure_cmds_exist('dpkg-repack', 'apt-ftparchive', '/usr/sbin/debootstrap')
    if os.getuid() != 0 and not options.u:
        error('can only run as root; maybe try -u?')
    if options.u:
        ensure_cmds_exist('fakeroot', 'fakechroot')
    mkemptydir(options.target)
    packages = get_packages()
    base = {
        pkg
        for pkg in packages.values()
        if pkg.essential
    }
    base |= {
        packages[pkg]
        for pkg in options.include.split(',')
    }
    trans_base = set()
    todo = base.copy()
    while todo:
        pkg = todo.pop()
        for dep in pkg.depends:
            # FIXME: take into account version constraints
            for alt in dep:
                try:
                    dep = packages[alt['name']]
                except KeyError:
                    pass
                else:
                    break
            else:
                dep_str = str.join(' | ', (alt['name'] for alt in dep))
                raise RuntimeError(f'Could not resolve dependency: {pkg} -> {dep_str}')
            if dep not in trans_base:
                todo.add(dep)
        trans_base.add(pkg)
    repository = tempfile.mkdtemp(prefix='demoostrap.', suffix='.apt')
    try:
        create_apt_archive(trans_base, repository)
        debootstrap(repository, options.target, include=options.include, no_root=options.u)
    finally:
        shutil.rmtree(repository)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
